[metadata]
name = svglib-st
version = 1.5.3
description = A pure-Python library for reading and converting SVG
long_description = file: README.rst
keywords =
    SVG
    PDF
    reportlab
    conversion
    graphics
url = https://github.com/deeplook/svglib
author = Dinu Gherman
author_email = gherman@darwin.in-berlin.de
license = LGPL 3
license_files = LICENSE.txt
classifiers =
    Development Status :: 5 - Production/Stable
    Environment :: Console
    Intended Audience :: End Users/Desktop
    Intended Audience :: Developers
    Operating System :: MacOS :: MacOS X
    Operating System :: Microsoft :: Windows
    Operating System :: POSIX
    Natural Language :: English
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Topic :: Documentation
    Topic :: Utilities
    Topic :: Printing
    Topic :: Multimedia :: Graphics :: Graphics Conversion
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: Text Processing :: Markup :: XML

[options]
python_requires = >=3.10
scripts =
    scripts/svg2pdf

[options.data_files]
share/man/man1 = svg2pdf.1

[aliases]
test = pytest

[flake8]
max-line-length = 99
