name: CI
on:
  push:
    branches:
      - scantrust
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: py${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        py: [ "3.10", "3.11", "3.12", "3.13" ]
        os: [ "ubuntu-latest", "macos-latest" ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: "Install dependencies"
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements.test.txt

      # other tests with the wikipedia stuff are failing, don't run them
      - name: Run Tests
        run: |
          python -m pytest tests/test_basic.py
          python -m pytest tests/test_fonts.py